name: orda
description: "A food ordering application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  go_router: ^13.0.0
  json_annotation: ^4.8.0
  signals: ^2.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
