name: orda
description: "A food ordering application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  cupertino_icons: ^1.0.6
  custom_sliding_segmented_control: ^1.8.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  json_annotation: ^4.8.0
  logger: ^2.0.2+1
  signals: ^2.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
